version: '3.8'
services:
  # mysql:
  #   image: mysql:5.7.31
  #   container_name: ProductDatabase
  #   deploy:
  #     replicas: 1
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password123
  #   ports:
  #     - 3306:3306
  # redis:
  #   image: redis
  #   container_name: redis
  #   command: ['redis-server', '--requirepass', 'password', '--appendonly', 'yes']
  #   deploy:
  #     replicas: 1
  #   environment:
  #     - REDIS_DISABLE_COMMANDS=FLUSHEDB,FLUSHALL
  #   ports:
  #     - 6379:6379
  # redis-commander:
  #   image: rediscommander/redis-commander
  #   container_name: rediscommander
  #   hostname: redis-commander
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379:0:password
  #   ports:
  #     - 8081:8081
